#server:
#  port: 8761
#eureka:
#  instance:
#    #主机名
#    hostname: localhost
#  client:
#    #eureka 注册中心地址
#    defaultZone: http://localhost:8762/eureka/

server:
  port: 8762
eureka:
  instance:
    #主机名
    hostname: localhost
  client:
    #eureka 注册中心地址
    defaultZone: http://localhost:8761/eureka/